services:
  test_cataloguedb:
    image: postgres:14
    # Requires write permissions if a /data/docker_volumes folder
    volumes:
    - /data/docker_volumes/catalogue:/var/lib/postgresql/data
    ports:
    - 127.0.0.1:5433:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: ${CATALOGUE_PASSWORD:?Catalogue DB  password is not set in prod.env file}
      POSTGRES_DB: cataloguedbtest
  object-storage:
    image: quay.io/minio/minio:RELEASE.2022-07-24T17-09-31Z
    # Requires write permissions if a /data/docker_volumes folder
    volumes:
    - /data/docker_volumes/storage:/data
    command: server --console-address ":9001" /data
    ports:
    - 127.0.0.1:9000:9000
    - 127.0.0.1:9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD:?Object storage password is not set in prod.env file}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
